/* VMukti 2.0 -- An Open Source Video Communications Suite
*
* Copyright (C) 2008 - 2009, VMukti Solutions Pvt. Ltd.
*
* Hardik Sanghvi <hardik@vmukti.com>
*
* See http://www.vmukti.com for more information about
* the VMukti project. Please do not directly contact
* any of the maintainers of this project for assistance;
* the project provides a web site, forums and mailing lists      
* for your use.

* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.

* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.

* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>
 
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace rptCRCbyCamp.Presentation {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCRCbyCamp")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCRCbyCamp : global::System.Data.DataSet {
        
        private dtCRCbyCampDataTable tabledtCRCbyCamp;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsCRCbyCamp() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsCRCbyCamp(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtCRCbyCamp"] != null)) {
                    base.Tables.Add(new dtCRCbyCampDataTable(ds.Tables["dtCRCbyCamp"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtCRCbyCampDataTable dtCRCbyCamp {
            get {
                return this.tabledtCRCbyCamp;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsCRCbyCamp cln = ((dsCRCbyCamp)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtCRCbyCamp"] != null)) {
                    base.Tables.Add(new dtCRCbyCampDataTable(ds.Tables["dtCRCbyCamp"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabledtCRCbyCamp = ((dtCRCbyCampDataTable)(base.Tables["dtCRCbyCamp"]));
            if ((initTable == true)) {
                if ((this.tabledtCRCbyCamp != null)) {
                    this.tabledtCRCbyCamp.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsCRCbyCamp";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsHistory.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtCRCbyCamp = new dtCRCbyCampDataTable();
            base.Tables.Add(this.tabledtCRCbyCamp);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtCRCbyCamp() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCRCbyCamp ds = new dsCRCbyCamp();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void dtCRCbyCampRowChangeEventHandler(object sender, dtCRCbyCampRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtCRCbyCampDataTable : global::System.Data.TypedTableBase<dtCRCbyCampRow> {
            
            private global::System.Data.DataColumn columnTalkTime;
            
            private global::System.Data.DataColumn columnA;
            
            private global::System.Data.DataColumn columnB;
            
            private global::System.Data.DataColumn columnCALLBK;
            
            private global::System.Data.DataColumn columnD1;
            
            private global::System.Data.DataColumn columnD2;
            
            private global::System.Data.DataColumn columnD3;
            
            private global::System.Data.DataColumn columnD3A;
            
            private global::System.Data.DataColumn columnD3I;
            
            private global::System.Data.DataColumn columnD3P;
            
            private global::System.Data.DataColumn columnDNC;
            
            private global::System.Data.DataColumn columnDT;
            
            private global::System.Data.DataColumn columnFAX;
            
            private global::System.Data.DataColumn columnHANG;
            
            private global::System.Data.DataColumn columnSALE;
            
            private global::System.Data.DataColumn columnCampaign;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampDataTable() {
                this.TableName = "dtCRCbyCamp";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtCRCbyCampDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtCRCbyCampDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TalkTimeColumn {
                get {
                    return this.columnTalkTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AColumn {
                get {
                    return this.columnA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BColumn {
                get {
                    return this.columnB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CALLBKColumn {
                get {
                    return this.columnCALLBK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D1Column {
                get {
                    return this.columnD1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D2Column {
                get {
                    return this.columnD2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3Column {
                get {
                    return this.columnD3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3AColumn {
                get {
                    return this.columnD3A;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3IColumn {
                get {
                    return this.columnD3I;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3PColumn {
                get {
                    return this.columnD3P;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DNCColumn {
                get {
                    return this.columnDNC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DTColumn {
                get {
                    return this.columnDT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXColumn {
                get {
                    return this.columnFAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HANGColumn {
                get {
                    return this.columnHANG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SALEColumn {
                get {
                    return this.columnSALE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CampaignColumn {
                get {
                    return this.columnCampaign;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampRow this[int index] {
                get {
                    return ((dtCRCbyCampRow)(this.Rows[index]));
                }
            }
            
            public event dtCRCbyCampRowChangeEventHandler dtCRCbyCampRowChanging;
            
            public event dtCRCbyCampRowChangeEventHandler dtCRCbyCampRowChanged;
            
            public event dtCRCbyCampRowChangeEventHandler dtCRCbyCampRowDeleting;
            
            public event dtCRCbyCampRowChangeEventHandler dtCRCbyCampRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtCRCbyCampRow(dtCRCbyCampRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampRow AdddtCRCbyCampRow(
                        string TalkTime, 
                        string A, 
                        string B, 
                        string CALLBK, 
                        string D1, 
                        string D2, 
                        string D3, 
                        string D3A, 
                        string D3I, 
                        string D3P, 
                        string DNC, 
                        string DT, 
                        string FAX, 
                        string HANG, 
                        string SALE, 
                        string Campaign) {
                dtCRCbyCampRow rowdtCRCbyCampRow = ((dtCRCbyCampRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TalkTime,
                        A,
                        B,
                        CALLBK,
                        D1,
                        D2,
                        D3,
                        D3A,
                        D3I,
                        D3P,
                        DNC,
                        DT,
                        FAX,
                        HANG,
                        SALE,
                        Campaign};
                rowdtCRCbyCampRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtCRCbyCampRow);
                return rowdtCRCbyCampRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtCRCbyCampDataTable cln = ((dtCRCbyCampDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtCRCbyCampDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnTalkTime = base.Columns["TalkTime"];
                this.columnA = base.Columns["A"];
                this.columnB = base.Columns["B"];
                this.columnCALLBK = base.Columns["CALLBK"];
                this.columnD1 = base.Columns["D1"];
                this.columnD2 = base.Columns["D2"];
                this.columnD3 = base.Columns["D3"];
                this.columnD3A = base.Columns["D3A"];
                this.columnD3I = base.Columns["D3I"];
                this.columnD3P = base.Columns["D3P"];
                this.columnDNC = base.Columns["DNC"];
                this.columnDT = base.Columns["DT"];
                this.columnFAX = base.Columns["FAX"];
                this.columnHANG = base.Columns["HANG"];
                this.columnSALE = base.Columns["SALE"];
                this.columnCampaign = base.Columns["Campaign"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnTalkTime = new global::System.Data.DataColumn("TalkTime", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTalkTime);
                this.columnA = new global::System.Data.DataColumn("A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnA);
                this.columnB = new global::System.Data.DataColumn("B", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB);
                this.columnCALLBK = new global::System.Data.DataColumn("CALLBK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCALLBK);
                this.columnD1 = new global::System.Data.DataColumn("D1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD1);
                this.columnD2 = new global::System.Data.DataColumn("D2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD2);
                this.columnD3 = new global::System.Data.DataColumn("D3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3);
                this.columnD3A = new global::System.Data.DataColumn("D3A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3A);
                this.columnD3I = new global::System.Data.DataColumn("D3I", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3I);
                this.columnD3P = new global::System.Data.DataColumn("D3P", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3P);
                this.columnDNC = new global::System.Data.DataColumn("DNC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDNC);
                this.columnDT = new global::System.Data.DataColumn("DT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT);
                this.columnFAX = new global::System.Data.DataColumn("FAX", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAX);
                this.columnHANG = new global::System.Data.DataColumn("HANG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHANG);
                this.columnSALE = new global::System.Data.DataColumn("SALE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALE);
                this.columnCampaign = new global::System.Data.DataColumn("Campaign", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaign);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampRow NewdtCRCbyCampRow() {
                return ((dtCRCbyCampRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtCRCbyCampRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtCRCbyCampRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtCRCbyCampRowChanged != null)) {
                    this.dtCRCbyCampRowChanged(this, new dtCRCbyCampRowChangeEvent(((dtCRCbyCampRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtCRCbyCampRowChanging != null)) {
                    this.dtCRCbyCampRowChanging(this, new dtCRCbyCampRowChangeEvent(((dtCRCbyCampRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtCRCbyCampRowDeleted != null)) {
                    this.dtCRCbyCampRowDeleted(this, new dtCRCbyCampRowChangeEvent(((dtCRCbyCampRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtCRCbyCampRowDeleting != null)) {
                    this.dtCRCbyCampRowDeleting(this, new dtCRCbyCampRowChangeEvent(((dtCRCbyCampRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtCRCbyCampRow(dtCRCbyCampRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCRCbyCamp ds = new dsCRCbyCamp();
                xs.Add(ds.GetSchemaSerializable());
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtCRCbyCampDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtCRCbyCampRow : global::System.Data.DataRow {
            
            private dtCRCbyCampDataTable tabledtCRCbyCamp;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtCRCbyCampRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtCRCbyCamp = ((dtCRCbyCampDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TalkTime {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.TalkTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TalkTime\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.TalkTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string A {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'A\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string B {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.BColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.BColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CALLBK {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.CALLBKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CALLBK\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.CALLBKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D1 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D1\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D2 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D2\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3A {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D3AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3A\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D3AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3I {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D3IColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3I\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D3IColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3P {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.D3PColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3P\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.D3PColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DNC {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.DNCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DNC\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.DNCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DT {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DT\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAX {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.FAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAX\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.FAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HANG {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.HANGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HANG\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.HANGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SALE {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.SALEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALE\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.SALEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Campaign {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyCamp.CampaignColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Campaign\' in table \'dtCRCbyCamp\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyCamp.CampaignColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTalkTimeNull() {
                return this.IsNull(this.tabledtCRCbyCamp.TalkTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTalkTimeNull() {
                this[this.tabledtCRCbyCamp.TalkTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsANull() {
                return this.IsNull(this.tabledtCRCbyCamp.AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetANull() {
                this[this.tabledtCRCbyCamp.AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBNull() {
                return this.IsNull(this.tabledtCRCbyCamp.BColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBNull() {
                this[this.tabledtCRCbyCamp.BColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCALLBKNull() {
                return this.IsNull(this.tabledtCRCbyCamp.CALLBKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCALLBKNull() {
                this[this.tabledtCRCbyCamp.CALLBKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD1Null() {
                return this.IsNull(this.tabledtCRCbyCamp.D1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD1Null() {
                this[this.tabledtCRCbyCamp.D1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD2Null() {
                return this.IsNull(this.tabledtCRCbyCamp.D2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD2Null() {
                this[this.tabledtCRCbyCamp.D2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3Null() {
                return this.IsNull(this.tabledtCRCbyCamp.D3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3Null() {
                this[this.tabledtCRCbyCamp.D3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3ANull() {
                return this.IsNull(this.tabledtCRCbyCamp.D3AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3ANull() {
                this[this.tabledtCRCbyCamp.D3AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3INull() {
                return this.IsNull(this.tabledtCRCbyCamp.D3IColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3INull() {
                this[this.tabledtCRCbyCamp.D3IColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3PNull() {
                return this.IsNull(this.tabledtCRCbyCamp.D3PColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3PNull() {
                this[this.tabledtCRCbyCamp.D3PColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDNCNull() {
                return this.IsNull(this.tabledtCRCbyCamp.DNCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDNCNull() {
                this[this.tabledtCRCbyCamp.DNCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDTNull() {
                return this.IsNull(this.tabledtCRCbyCamp.DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDTNull() {
                this[this.tabledtCRCbyCamp.DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXNull() {
                return this.IsNull(this.tabledtCRCbyCamp.FAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXNull() {
                this[this.tabledtCRCbyCamp.FAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHANGNull() {
                return this.IsNull(this.tabledtCRCbyCamp.HANGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHANGNull() {
                this[this.tabledtCRCbyCamp.HANGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSALENull() {
                return this.IsNull(this.tabledtCRCbyCamp.SALEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSALENull() {
                this[this.tabledtCRCbyCamp.SALEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCampaignNull() {
                return this.IsNull(this.tabledtCRCbyCamp.CampaignColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCampaignNull() {
                this[this.tabledtCRCbyCamp.CampaignColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtCRCbyCampRowChangeEvent : global::System.EventArgs {
            
            private dtCRCbyCampRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampRowChangeEvent(dtCRCbyCampRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyCampRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591