using System;
using rptQuestionAnswers.DataAccess;

namespace rptQuestionAnswers.Business
{
    public class ClsRptQuestionAnswersCollection : ClsBaseCollection<ClsRptQuestionAnswers>
    {
        //public static ClsRptQuestionAnswersCollection GetAll(int ScriptID)
        //{
        //    ClsRptQuestionAnswersCollection obj = new ClsRptQuestionAnswersCollection();
        //    return obj;
        //}
    }
}
