//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace rptCRCbyAgent.Presentation {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCRCbyAgent")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCRCbyAgent : global::System.Data.DataSet {
        
        private dtCRCbyAgentDataTable tabledtCRCbyAgent;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsCRCbyAgent() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsCRCbyAgent(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtCRCbyAgent"] != null)) {
                    base.Tables.Add(new dtCRCbyAgentDataTable(ds.Tables["dtCRCbyAgent"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtCRCbyAgentDataTable dtCRCbyAgent {
            get {
                return this.tabledtCRCbyAgent;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsCRCbyAgent cln = ((dsCRCbyAgent)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtCRCbyAgent"] != null)) {
                    base.Tables.Add(new dtCRCbyAgentDataTable(ds.Tables["dtCRCbyAgent"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabledtCRCbyAgent = ((dtCRCbyAgentDataTable)(base.Tables["dtCRCbyAgent"]));
            if ((initTable == true)) {
                if ((this.tabledtCRCbyAgent != null)) {
                    this.tabledtCRCbyAgent.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsCRCbyAgent";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsHistory.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtCRCbyAgent = new dtCRCbyAgentDataTable();
            base.Tables.Add(this.tabledtCRCbyAgent);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtCRCbyAgent() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCRCbyAgent ds = new dsCRCbyAgent();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void dtCRCbyAgentRowChangeEventHandler(object sender, dtCRCbyAgentRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtCRCbyAgentDataTable : global::System.Data.TypedTableBase<dtCRCbyAgentRow> {
            
            private global::System.Data.DataColumn columnTalkTime;
            
            private global::System.Data.DataColumn columnA;
            
            private global::System.Data.DataColumn columnB;
            
            private global::System.Data.DataColumn columnCALLBK;
            
            private global::System.Data.DataColumn columnD1;
            
            private global::System.Data.DataColumn columnD2;
            
            private global::System.Data.DataColumn columnD3;
            
            private global::System.Data.DataColumn columnD3A;
            
            private global::System.Data.DataColumn columnD3I;
            
            private global::System.Data.DataColumn columnD3P;
            
            private global::System.Data.DataColumn columnDNC;
            
            private global::System.Data.DataColumn columnDT;
            
            private global::System.Data.DataColumn columnFAX;
            
            private global::System.Data.DataColumn columnHANG;
            
            private global::System.Data.DataColumn columnSALE;
            
            private global::System.Data.DataColumn columnCampaign;
            
            private global::System.Data.DataColumn columnUsername;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentDataTable() {
                this.TableName = "dtCRCbyAgent";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtCRCbyAgentDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtCRCbyAgentDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TalkTimeColumn {
                get {
                    return this.columnTalkTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AColumn {
                get {
                    return this.columnA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BColumn {
                get {
                    return this.columnB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CALLBKColumn {
                get {
                    return this.columnCALLBK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D1Column {
                get {
                    return this.columnD1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D2Column {
                get {
                    return this.columnD2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3Column {
                get {
                    return this.columnD3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3AColumn {
                get {
                    return this.columnD3A;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3IColumn {
                get {
                    return this.columnD3I;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn D3PColumn {
                get {
                    return this.columnD3P;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DNCColumn {
                get {
                    return this.columnDNC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DTColumn {
                get {
                    return this.columnDT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXColumn {
                get {
                    return this.columnFAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HANGColumn {
                get {
                    return this.columnHANG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SALEColumn {
                get {
                    return this.columnSALE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CampaignColumn {
                get {
                    return this.columnCampaign;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UsernameColumn {
                get {
                    return this.columnUsername;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentRow this[int index] {
                get {
                    return ((dtCRCbyAgentRow)(this.Rows[index]));
                }
            }
            
            public event dtCRCbyAgentRowChangeEventHandler dtCRCbyAgentRowChanging;
            
            public event dtCRCbyAgentRowChangeEventHandler dtCRCbyAgentRowChanged;
            
            public event dtCRCbyAgentRowChangeEventHandler dtCRCbyAgentRowDeleting;
            
            public event dtCRCbyAgentRowChangeEventHandler dtCRCbyAgentRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtCRCbyAgentRow(dtCRCbyAgentRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentRow AdddtCRCbyAgentRow(
                        string TalkTime, 
                        string A, 
                        string B, 
                        string CALLBK, 
                        string D1, 
                        string D2, 
                        string D3, 
                        string D3A, 
                        string D3I, 
                        string D3P, 
                        string DNC, 
                        string DT, 
                        string FAX, 
                        string HANG, 
                        string SALE, 
                        string Campaign, 
                        string Username) {
                dtCRCbyAgentRow rowdtCRCbyAgentRow = ((dtCRCbyAgentRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TalkTime,
                        A,
                        B,
                        CALLBK,
                        D1,
                        D2,
                        D3,
                        D3A,
                        D3I,
                        D3P,
                        DNC,
                        DT,
                        FAX,
                        HANG,
                        SALE,
                        Campaign,
                        Username};
                rowdtCRCbyAgentRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtCRCbyAgentRow);
                return rowdtCRCbyAgentRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtCRCbyAgentDataTable cln = ((dtCRCbyAgentDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtCRCbyAgentDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnTalkTime = base.Columns["TalkTime"];
                this.columnA = base.Columns["A"];
                this.columnB = base.Columns["B"];
                this.columnCALLBK = base.Columns["CALLBK"];
                this.columnD1 = base.Columns["D1"];
                this.columnD2 = base.Columns["D2"];
                this.columnD3 = base.Columns["D3"];
                this.columnD3A = base.Columns["D3A"];
                this.columnD3I = base.Columns["D3I"];
                this.columnD3P = base.Columns["D3P"];
                this.columnDNC = base.Columns["DNC"];
                this.columnDT = base.Columns["DT"];
                this.columnFAX = base.Columns["FAX"];
                this.columnHANG = base.Columns["HANG"];
                this.columnSALE = base.Columns["SALE"];
                this.columnCampaign = base.Columns["Campaign"];
                this.columnUsername = base.Columns["Username"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnTalkTime = new global::System.Data.DataColumn("TalkTime", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTalkTime);
                this.columnA = new global::System.Data.DataColumn("A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnA);
                this.columnB = new global::System.Data.DataColumn("B", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB);
                this.columnCALLBK = new global::System.Data.DataColumn("CALLBK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCALLBK);
                this.columnD1 = new global::System.Data.DataColumn("D1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD1);
                this.columnD2 = new global::System.Data.DataColumn("D2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD2);
                this.columnD3 = new global::System.Data.DataColumn("D3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3);
                this.columnD3A = new global::System.Data.DataColumn("D3A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3A);
                this.columnD3I = new global::System.Data.DataColumn("D3I", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3I);
                this.columnD3P = new global::System.Data.DataColumn("D3P", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnD3P);
                this.columnDNC = new global::System.Data.DataColumn("DNC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDNC);
                this.columnDT = new global::System.Data.DataColumn("DT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT);
                this.columnFAX = new global::System.Data.DataColumn("FAX", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAX);
                this.columnHANG = new global::System.Data.DataColumn("HANG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHANG);
                this.columnSALE = new global::System.Data.DataColumn("SALE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALE);
                this.columnCampaign = new global::System.Data.DataColumn("Campaign", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaign);
                this.columnUsername = new global::System.Data.DataColumn("Username", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUsername);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentRow NewdtCRCbyAgentRow() {
                return ((dtCRCbyAgentRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtCRCbyAgentRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtCRCbyAgentRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtCRCbyAgentRowChanged != null)) {
                    this.dtCRCbyAgentRowChanged(this, new dtCRCbyAgentRowChangeEvent(((dtCRCbyAgentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtCRCbyAgentRowChanging != null)) {
                    this.dtCRCbyAgentRowChanging(this, new dtCRCbyAgentRowChangeEvent(((dtCRCbyAgentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtCRCbyAgentRowDeleted != null)) {
                    this.dtCRCbyAgentRowDeleted(this, new dtCRCbyAgentRowChangeEvent(((dtCRCbyAgentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtCRCbyAgentRowDeleting != null)) {
                    this.dtCRCbyAgentRowDeleting(this, new dtCRCbyAgentRowChangeEvent(((dtCRCbyAgentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtCRCbyAgentRow(dtCRCbyAgentRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCRCbyAgent ds = new dsCRCbyAgent();
                xs.Add(ds.GetSchemaSerializable());
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtCRCbyAgentDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtCRCbyAgentRow : global::System.Data.DataRow {
            
            private dtCRCbyAgentDataTable tabledtCRCbyAgent;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtCRCbyAgentRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtCRCbyAgent = ((dtCRCbyAgentDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TalkTime {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.TalkTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TalkTime\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.TalkTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string A {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'A\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string B {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.BColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.BColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CALLBK {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.CALLBKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CALLBK\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.CALLBKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D1 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D1\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D2 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D2\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3 {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3A {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D3AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3A\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D3AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3I {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D3IColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3I\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D3IColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string D3P {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.D3PColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'D3P\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.D3PColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DNC {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.DNCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DNC\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.DNCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DT {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DT\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAX {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.FAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAX\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.FAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HANG {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.HANGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HANG\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.HANGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SALE {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.SALEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALE\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.SALEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Campaign {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.CampaignColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Campaign\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.CampaignColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Username {
                get {
                    try {
                        return ((string)(this[this.tabledtCRCbyAgent.UsernameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Username\' in table \'dtCRCbyAgent\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtCRCbyAgent.UsernameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTalkTimeNull() {
                return this.IsNull(this.tabledtCRCbyAgent.TalkTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTalkTimeNull() {
                this[this.tabledtCRCbyAgent.TalkTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsANull() {
                return this.IsNull(this.tabledtCRCbyAgent.AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetANull() {
                this[this.tabledtCRCbyAgent.AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBNull() {
                return this.IsNull(this.tabledtCRCbyAgent.BColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBNull() {
                this[this.tabledtCRCbyAgent.BColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCALLBKNull() {
                return this.IsNull(this.tabledtCRCbyAgent.CALLBKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCALLBKNull() {
                this[this.tabledtCRCbyAgent.CALLBKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD1Null() {
                return this.IsNull(this.tabledtCRCbyAgent.D1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD1Null() {
                this[this.tabledtCRCbyAgent.D1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD2Null() {
                return this.IsNull(this.tabledtCRCbyAgent.D2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD2Null() {
                this[this.tabledtCRCbyAgent.D2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3Null() {
                return this.IsNull(this.tabledtCRCbyAgent.D3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3Null() {
                this[this.tabledtCRCbyAgent.D3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3ANull() {
                return this.IsNull(this.tabledtCRCbyAgent.D3AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3ANull() {
                this[this.tabledtCRCbyAgent.D3AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3INull() {
                return this.IsNull(this.tabledtCRCbyAgent.D3IColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3INull() {
                this[this.tabledtCRCbyAgent.D3IColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsD3PNull() {
                return this.IsNull(this.tabledtCRCbyAgent.D3PColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetD3PNull() {
                this[this.tabledtCRCbyAgent.D3PColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDNCNull() {
                return this.IsNull(this.tabledtCRCbyAgent.DNCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDNCNull() {
                this[this.tabledtCRCbyAgent.DNCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDTNull() {
                return this.IsNull(this.tabledtCRCbyAgent.DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDTNull() {
                this[this.tabledtCRCbyAgent.DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXNull() {
                return this.IsNull(this.tabledtCRCbyAgent.FAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXNull() {
                this[this.tabledtCRCbyAgent.FAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHANGNull() {
                return this.IsNull(this.tabledtCRCbyAgent.HANGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHANGNull() {
                this[this.tabledtCRCbyAgent.HANGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSALENull() {
                return this.IsNull(this.tabledtCRCbyAgent.SALEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSALENull() {
                this[this.tabledtCRCbyAgent.SALEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCampaignNull() {
                return this.IsNull(this.tabledtCRCbyAgent.CampaignColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCampaignNull() {
                this[this.tabledtCRCbyAgent.CampaignColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUsernameNull() {
                return this.IsNull(this.tabledtCRCbyAgent.UsernameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUsernameNull() {
                this[this.tabledtCRCbyAgent.UsernameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtCRCbyAgentRowChangeEvent : global::System.EventArgs {
            
            private dtCRCbyAgentRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentRowChangeEvent(dtCRCbyAgentRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtCRCbyAgentRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591